<Project>

  <!--
    PROPERTIES
  -->

  <!--
    PROJECT BUILD (USER-OVERRIDABLE) PROPERTIES
  -->
  <PropertyGroup>
    <WinExeTargetFrameworks>net10.0-windows</WinExeTargetFrameworks>
    <WinTestTargetFrameworks>net10.0-windows;net9.0-windows;net8.0-windows;net48</WinTestTargetFrameworks>
    <WinLibTargetFrameworks>net10.0-windows;net9.0-windows;net8.0-windows;net48</WinLibTargetFrameworks>
    <ExeTargetFrameworks>net10.0</ExeTargetFrameworks>
    <TestTargetFrameworks>net10.0;net9.0;net8.0;net48</TestTargetFrameworks>
    <LibTargetFrameworks>net10.0;net9.0;net8.0;net48</LibTargetFrameworks>

    <LangVersion>latest</LangVersion>

    <!--
      CA2252: Opt in to preview features before using them
      https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2252
    -->
    <EnablePreviewFeatures>false</EnablePreviewFeatures>

    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>

    <AssemblyOriginatorKeyFileName>public.snk</AssemblyOriginatorKeyFileName>
  </PropertyGroup>

  <PropertyGroup>
    <Product>Wpf.Effects</Product>
    <Authors>Maximilian Haru Raditya</Authors>
    <Company>Maximilian Haru Raditya</Company>
    <CurrentYear>$([System.DateTime]::Now.ToString("yyyy"))</CurrentYear>
    <Copyright>© 2008-$(CurrentYear) Wpf.Effects - https://github.com/mahara/Wpf.Effects</Copyright>

    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/mahara/Wpf.Effects</PackageProjectUrl>
    <!--<PackageIcon>Wpf.Effects-logo.png</PackageIcon>-->
    <RepositoryUrl>https://github.com/mahara/Wpf.Effects</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <ItemGroup>
    <!--<Content Include="$(WorkspaceFolderPath)assets\media\images\Wpf.Effects-logo.png" Link="Properties\Wpf.Effects-logo.png" Pack="true" PackagePath="\" />-->
  </ItemGroup>

</Project>
